Repository 42organization/42gg.client, pull requests merged in 2023-11, with the labels that each got.

#1078 Feat/유저 토너먼트 전적 페이지 레이아웃 #1077
  pages/tournament-record.tsx
  styles/tournament-record/TournamentRecord.module.scss
Labels: enhancement, user

#1082 Feat/관리자 토너먼트 페이지 레이아웃#1075
  components/admin/SideNav.tsx
  components/admin/tournament/TournamentEdit.tsx
  components/admin/tournament/TournamentList.tsx
  constants/admin/table.ts
  pages/admin/tournament.tsx
  types/admin/adminTournamentTypes.ts
  types/admin/tableTypes.ts
Labels: enhancement, admin

#1085 [Feat]토너먼트 type 통일 #1084
  components/admin/tournament/TournamentList.tsx
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  pages/tournament.tsx
  types/admin/adminTournamentTypes.ts
  types/modalTypes.ts
  types/tournamentTypes.ts
Labels: refactor

#1086 Feat/유저 토너먼트 전적 페이지 우승자 스와이프 뷰 #1070
  components/tournament-record/WinnerSwipeView.tsx
  package-lock.json
  package.json
  pages/tournament-record.tsx
  styles/tournament-record/WinnerSwipeView.module.scss
Labels: enhancement, user

#1087 [Feat] 토너먼트 페이지 api#1083
  components/modal/ModalButton.tsx
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  pages/tournament.tsx
  styles/common.scss
  styles/modal/event/TournamentRegistryModal.module.scss
Labels: enhancement

#1091 [Feat] 토너먼트 전체조회 API mock #1089
  pages/api/pingpong/tournaments/index.ts
Labels: enhancement, user

#1093 [Feat] 무한스크롤 제네릭 함수 #1092
  utils/infinityScroll.ts
Labels: enhancement

#1095 [Feat] TournamentData 타입 추가 #1094
  types/tournamentTypes.ts
Labels: enhancement

#1097 [Fix] 토너먼트전체조회 Mock API 페이지네이션 로직 수정 #1096
  pages/api/pingpong/tournaments/index.ts
Labels: bug

#1099 Feat/유저 토너먼트 전적 페이지 우승자 스와이퍼 슬라이드 mock api #1088
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwipeView.tsx
  components/tournament-record/WinnerSwiper.tsx
  components/tournament/TournamentCard.tsx
  pages/api/pingpong/tournament/dummyTournamentData.ts
  pages/api/pingpong/tournament/index.ts
  pages/api/pingpong/tournaments/index.ts
  pages/tournament-record.tsx
  pages/tournament.tsx
  styles/tournament-record/WinnerProfileImage.module.scss
  styles/tournament-record/WinnerSwipeView.module.scss
  styles/tournament-record/WinnerSwiper.module.scss
  types/tournamentTypes.ts
  utils/infinityScroll.ts
Labels: enhancement, user

#1101 Feat/관리자 토너먼트 페이지 전적 수정을 위한 브래킷뷰#1080
  components/admin/tournament/TournamentList.tsx
  components/modal/admin/AdminEditTournamentBraket.tsx
  components/modal/modalType/AdminModal.tsx
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentMatch.tsx
  constants/admin/table.ts
  package-lock.json
  package.json
  public/image/match_qustion.png
  styles/PlayerImage.module.scss
  styles/admin/modal/AdminEditTournamentBraket.module.scss
  styles/tournament/TournamentMatch.module.scss
  types/modalTypes.ts
Labels: enhancement, admin

#1100 [Feat] 토너먼트 페이지 인피니티 스크롤#1090
  components/main/Section.tsx
  components/tournament/TournamentMegaphone.tsx
  pages/tournament.tsx
  styles/tournament/TournamentContainer.module.scss
Labels: enhancement, user

#1105 Feat/유저 토너먼트 전적 페이지 토너먼트 정보 표시 #1104
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwiper.tsx
  pages/api/pingpong/tournament/dummyTournamentData.ts
  pages/tournament-record.tsx
  pages/tournament.tsx
  types/tournamentTypes.ts
Labels: enhancement, user

#1107 Feat/유저 토너먼트 전적 페이지 리그 선택 버튼 #1079
  components/tournament-record/LeagueButtonGroup.tsx
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwiper.tsx
  pages/tournament-record.tsx
  styles/tournament-record/LeagueButtonGroup.module.scss
  styles/tournament-record/TournamentRecord.module.scss
Labels: enhancement, user

#1109 Feat/메뉴바에 tournament record(명예의전당) 바로가기 추가 #1108
  components/Layout/MenuBar/MenuBarElement.tsx
  public/image/menu_halloffame.svg
Labels: enhancement, user

#1110 Feat/우승자 슬라이드 애니메이션 및 이미지 로드 실패 시 fall back 이미지 #1098
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwiper.tsx
  styles/tournament-record/WinnerProfileImage.module.scss
Labels: enhancement, user

#1117 [Feat] 관리자 토너먼트 참가자 수정 모달 컴포넌트 추가 및 UI #1113
  components/modal/admin/AdminTournamentParticipantEditModal.tsx
  components/modal/modalType/AdminModal.tsx
  styles/admin/modal/AdminTournamentParticipantEditModal.module.scss
  types/modalTypes.ts
Labels: enhancement, admin

#1118 Feat/관리자 토너먼트 페이지 생성수정삭제 버튼 #1112
  components/admin/tournament/TournamentEdit.tsx
  components/admin/tournament/TournamentList.tsx
  components/modal/admin/AdminEditTournamentBraket.tsx
  constants/admin/table.ts
  hooks/tournament/useTournamentEditInfo.ts
  pages/admin/tournament.tsx
  pages/api/pingpong/tournament/dummyTournamentData.ts
  styles/admin/modal/AdminEditTournamentBraket.module.scss
  styles/admin/tournament/Tournament.module.scss
  styles/admin/tournament/TournamentEdit.module.scss
  styles/admin/tournament/TournamentList.module.scss
  types/admin/adminTournamentTypes.ts
Labels: enhancement, admin

#1123 Feat/관리자 토너먼트 유저 전체조회, 추가 및 삭제 mock api #1119
  pages/api/pingpong/admin/tournament/[tournamentId]/users/[userId].ts
  pages/api/pingpong/admin/tournament/[tournamentId]/users/index.ts
  types/admin/adminTournamentTypes.ts
Labels: enhancement, admin

#1126 Feat/관리자 토너먼트 참가자 수정 모달 유저 검색 기능 #1120
  components/admin/tournament/TournamentSearchBarGroup.tsx
  components/modal/admin/AdminTournamentParticipantEditModal.tsx
  package-lock.json
  package.json
Labels: enhancement, admin
