Repository 42organization/42gg.client, pull requests merged in 2023-12, with the labels that each got.

#1137 Others/토너먼트 페이지 토너먼트 모달 style 작업#1128
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentCard.tsx
  components/tournament/TournamentMegaphone.tsx
  pages/api/pingpong/tournament/[tournamentId]/users/dummyData.ts
  pages/api/pingpong/tournament/[tournamentId]/users/index.ts
  pages/api/pingpong/tournament/index.ts
  pages/tournament.tsx
  styles/modal/event/TournamentRegistryModal.module.scss
  styles/tournament/TournamentCard.module.scss
  styles/tournament/TournamentContainer.module.scss
Labels: enhancement, user

#1136 Feat/관리자 토너먼트 페이지 api 연동 #1131
  components/admin/tournament/TournamentEdit.tsx
  components/admin/tournament/TournamentList.tsx
  components/modal/admin/AdminEditTournamentBraket.tsx
Labels: enhancement, admin

#1140 Feat/관리자 토너먼트 페이지 유저 수정 모달 UI 및 mock api 연동 #1134
  components/admin/tournament/TournamentList.tsx
  components/admin/tournament/TournamentSearchBarGroup.tsx
  components/modal/admin/AdminTournamentParticipantEditModal.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminSearchUserDropDownMenu.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamenSearchBar.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentParticipantEditModal.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentParticipantList.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentSearchBarGroup.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournemntParticipantDeleteConfirmInput.tsx
  components/modal/modalType/AdminModal.tsx
  hooks/admin/modal/useAdminSearchUser.ts
  hooks/admin/modal/useAdminTournamentParticipantEdit.ts
  pages/api/pingpong/admin/tournaments/[tournamentId]/users/[userId].ts
  pages/api/pingpong/admin/tournaments/[tournamentId]/users/index.ts
  styles/admin/modal/AdminTournamentParticipantEditModal.module.scss
  types/admin/adminTournamentTypes.ts
Labels: enhancement, admin

#1145 [Refactor] 토너먼트 게임 요청 useQuery 및 시간 지연 로직 삭제 #1144
  components/tournament-record/UserTournamentBracket.tsx
Labels: enhancement, user

#1152 [Feat] 랜딩페이지 토너먼트 배너 UI 변경 #1149
  components/main/Section.tsx
  components/main/TournamentPreview/TournamentPreview.tsx
  components/main/TournamentPreview/TournamentPreviewItem.tsx
  components/tournament/TournamentMegaphone.tsx
  hooks/tournament/useBeforeLiveTournamentData.ts
  pages/index.tsx
  styles/main/TournamentPreview/TournamentPreview.module.scss
  styles/main/TournamentPreview/TournamentPreviewItem.module.scss
  utils/handleTime.ts
Labels: enhancement, user

#1133 Feat/유저 토너먼트 전적 페이지 api 연동 #1074
  components/tournament-record/UserTournamentBracket.tsx
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwiper.tsx
  components/tournament-record/WinnerTournamentInfo.tsx
  pages/tournament-record.tsx
  styles/tournament-record/TournamentRecord.module.scss
  styles/tournament-record/WinnerTournamentInfo.module.scss
Labels: enhancement, user

#1154 Feat/관리자 토너먼트 유저 관리 api 연동 #1153
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentParticipantList.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentSearchBarGroup.tsx
  hooks/admin/modal/useAdminSearchUser.ts
  hooks/admin/modal/useAdminTournamentParticipantEdit.ts
Labels: enhancement, admin

#1155 Feat/관리자 토너먼트 페이지 브래킷뷰 수정 기능 구현 #1125
  components/admin/tournament/TournamentEditBraket.tsx
  components/admin/tournament/TournamentEditMatch.tsx
  components/admin/tournament/TournamentList.tsx
  components/modal/admin/AdminEditTournamentBraket.tsx
  hooks/tournament/useTournamentMatchEditor.ts
  pages/api/pingpong/tournament/[tournamentId]/games/dummyTournamentGame.ts
  pages/api/pingpong/tournament/[tournamentId]/games/generateTournamentGames.ts
  pages/tournament.tsx
  stories/game/GameResultBigItem.stories.tsx
  stories/game/GameResultSmallItem.stories.tsx
  styles/admin/modal/AdminEditTournamentBraket.module.scss
  styles/admin/tournament/TournamentEditMatch.module.scss
  types/gameTypes.ts
  types/tournamentTypes.ts
  utils/handleTournamentGame.ts
Labels: enhancement, admin

#1146 [Feat] 브라켓 뷰 클릭시 하이라이트 표기#1138
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentCard.tsx
  components/tournament/TournamentMatch.tsx
  pages/tournament.tsx
  styles/tournament/TournamentCard.module.scss
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/TournamentMatch.module.scss
  utils/recoil/tournament.ts
Labels: enhancement, user

#1151 [Fix] 토너먼트 전체 조회 api 연결 #1150
  components/modal/tournament/TournamentRegistryModal.tsx
  pages/tournament.tsx
Labels: enhancement, user

#1163 [Fix] 모바일 환경에서 브라켓 뷰 하이라이트 안됨#1161
  components/tournament/TournamentMatch.tsx
  pages/tournament.tsx
Labels: bug

#1165 [Fix] 토너먼트 card style 수정#1159
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  styles/tournament/TournamentCard.module.scss
Labels: enhancement, user

#1164 [Others] 유저 토너먼트 전적 페이지 UI 변경 #1160
  components/tournament-record/WinnerProfileImage.tsx
  components/tournament-record/WinnerSwiper.tsx
  pages/tournament-record.tsx
  styles/tournament-record/TournamentRecord.module.scss
  styles/tournament-record/WinnerProfileImage.module.scss
  styles/tournament-record/WinnerSwiper.module.scss
  styles/tournament-record/WinnerTournamentInfo.module.scss
Labels: user

#1166 [Fix] 점수 수정 request 수정 #1131
  hooks/tournament/useTournamentMatchEditor.ts
Labels: enhancement, admin

#1170 [Fix] 메인 페이지 토너먼트 미리보기 유효성 검사 수정 #1169
  pages/index.tsx
Labels: bug, user

#1172 Others/토너먼트 card 모바일 style 수정 및 api 최적화#1168
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  pages/index.tsx
  pages/tournament.tsx
  styles/modal/event/TournamentRegistryModal.module.scss
  styles/tournament/TournamentCard.module.scss
  styles/tournament/TournamentContainer.module.scss
  utils/handleBraketSize.ts
Labels: enhancement, refactor

#1184 Feat/관리자 토너먼트 페이지 api 연동 #1131
  components/admin/tournament/TournamentEdit.tsx
  components/admin/tournament/TournamentEditMatch.tsx
  components/admin/tournament/TournamentList.tsx
  components/admin/tournament/TournamentModalPreview.tsx
  components/tournament/TournamentMatch.tsx
  hooks/tournament/useTournamentEditInfo.ts
  pages/api/pingpong/tournaments/[tournamentId]/games/dummyTournamentGame.ts
  pages/api/pingpong/tournaments/[tournamentId]/games/generateTournamentGames.ts
  pages/api/pingpong/tournaments/[tournamentId]/games/index.ts
  pages/api/pingpong/tournaments/[tournamentId]/users/dummyData.ts
  pages/api/pingpong/tournaments/[tournamentId]/users/index.ts
  pages/api/pingpong/tournaments/dummyTournamentData.ts
  pages/api/pingpong/tournaments/index.ts
  styles/admin/tournament/TournamentEditMatch.module.scss
  styles/tournament/TournamentMatch.module.scss
  types/admin/adminTournamentTypes.ts
  utils/handleTime.ts
  utils/handleTournamentGame.ts
Labels: enhancement, admin

#1183 Others/일반랭크 게임 결과 조회 api 통합 #1181
  components/modal/statChange/StatChangeModal.tsx
Labels: user, refactor

#1185 [Fix] 이미지 위치 수정 #1162
  components/tournament/TournamentMatch.tsx
  styles/tournament/TournamentMatch.module.scss
Labels: bug, admin, user

#1180 [fix] escape함수를 통한 문자열 치환 #1179
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentMatch.tsx
  hooks/admin/modal/useAdminSearchUser.ts
  hooks/tournament/useTournamentMatchEditor.ts
Labels: admin

#1191 [Fix] 점수 입력 모달 클릭 안 됨 #1190
  components/modal/statChange/StatChangeModal.tsx
  components/tournament/TournamentMatch.tsx
Labels: bug, user

#1200 [Fix] TBD를 공백문자로 표시하도록 변환 #1199
  components/tournament/TournamentMatch.tsx
Labels: enhancement

#1198 [Others] 토너먼트 브라켓 매치 상태에 따른 bouncing dots UI #1173
  components/Layout/Layout.tsx
  components/UI/BouncingDots.tsx
  components/UI/EmptyImage.tsx
  components/UI/StyledButton.tsx
  components/store/InventoryList.tsx
  components/tournament/TournamentMatch.tsx
  pages/index.tsx
  pages/login.tsx
  styles/UI/BouncingDots.module.scss
  styles/UI/EmptyImage.module.scss
  styles/UI/StyledButton.module.scss
  styles/tournament/TournamentMatch.module.scss
Labels: user

#1202 Feat/진행중인 토너먼트의 내용 보여주기#1195
  components/main/TournamentPreview/TournamentPreview.tsx
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  pages/tournament.tsx
  styles/tournament/TournamentCard.module.scss
  styles/tournament/TournamentContainer.module.scss
Labels: enhancement

#1201 [Others] 관리자 토너먼트 유저 추가 검색창 수정 #1175
  components/modal/admin/AdminEditTournamentBraket.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminSearchUserDropDownMenu.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamenSearchBar.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentParticipantEditModal.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentParticipantList.tsx
  components/modal/admin/AdminTournamentParticipantEditModal/AdminTournamentSearchBarGroup.tsx
  components/tournament-record/WinnerSwiper.tsx
  hooks/admin/modal/useAdminSearchUser.ts
  pages/tournament.tsx
  styles/admin/modal/AdminTournamentParticipantEditModal.module.scss
Labels: admin

#1206 [Fix] 변수명 수정 #1205
  components/admin/tournament/TournamentEditMatch.tsx
  components/modal/tournament/TournamentRegistryModal.tsx
  components/tournament/TournamentCard.tsx
  pages/api/pingpong/tournaments/dummyTournamentData.ts
  types/admin/adminTournamentTypes.ts
  types/tournamentTypes.ts
Labels: bug

#1219 Update README.md
  README.md
Labels: documentation
