Repository 42organization/42gg.client, pull requests merged in 2024-08, with the labels that each got.

#1466 [Feat] agenda axios setting #1460
  components/agenda/agendaDetail/tabs/AgendaDescription.tsx
  components/agenda/utils/formatDate.tsx
  utils/axios.ts
Labels: enhancement

#1467 [Feat] profile layout #1446
  components/agenda/Profile/AgendaHistory.tsx
  components/agenda/Profile/AgendaUserSearchBar.tsx
  components/agenda/Profile/HistoryItem.tsx
  components/agenda/Profile/ParticipatingAgendaItem.tsx
  components/agenda/Profile/ParticipatingTeam.tsx
  components/agenda/Profile/ProfileContent.tsx
  components/agenda/Profile/ProfileImageCard.tsx
  pages/_app.tsx
  pages/agenda/profile/index.tsx
  public/image/agenda/42-icon.svg
  public/image/agenda/acheivement.svg
  public/image/agenda/github.svg
  public/image/agenda/jeongrol.jpeg
  public/styles/reset.css
  styles/agenda/Profile/AgendaHistory.module.scss
  styles/agenda/Profile/AgendaProfile.module.scss
  styles/agenda/Profile/AgendaUserSearchBar.module.scss
  styles/agenda/Profile/HistoryItem.module.scss
  styles/agenda/Profile/ParticipatingAgendaItem.module.scss
  styles/agenda/Profile/ParticipatingTeam.module.scss
  styles/agenda/Profile/ProfileContent.module.scss
  styles/agenda/Profile/ProfileImageCard.module.scss
  styles/agenda/common.scss
Labels: enhancement

#1471 [Feat] agenda 상세정보 api연결 및 필요한 UI 추가 #1464
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/AgendaTab.tsx
  components/agenda/agendaDetail/TabContent.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/AgendaConditions.tsx
  components/agenda/agendaDetail/tabs/AgendaDescription.tsx
  components/agenda/agendaDetail/tabs/AgendaParticipants.tsx
  components/agenda/agendaDetail/tabs/Participant.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeam.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  components/agenda/utils/coalition/countCoalitions.tsx
  components/agenda/utils/coalition/getCoalitionEnum.tsx
  constants/agenda/agenda.ts
  hooks/agenda/agendaDetail/useParticipant.ts
  hooks/agenda/agendaDetail/useParticipantTeam.ts
  hooks/agenda/useFetchDataGet.ts
  pages/agenda/[agendaKey]/index.tsx
  styles/agenda/agendaDetail/tabs/AgendaAnnouncements.module.scss
  styles/agenda/agendaDetail/tabs/ParticipantTeam.module.scss
  types/agenda/agendaDetail/agendaTypes.ts
  types/agenda/agendaDetail/tabs/agendaInfoTypes.ts
  types/agenda/agendaDetail/tabs/participantTeamTypes.ts
  types/agenda/agendaDetail/tabs/participantTypes.ts
  types/agenda/button/tabButtonTypes.ts
  types/agenda/coalitionTypes.ts
  types/agenda/profile/profileDataTypes.ts
  types/agenda/team/teamDataTypes.ts
Labels: enhancement, api

#1473 [Refactor] useFetchGet 함수명 및 인자 변경 #1464
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  hooks/agenda/agendaDetail/useParticipant.ts
  hooks/agenda/agendaDetail/useParticipantTeam.ts
  hooks/agenda/useFetchDataGet.ts
  hooks/agenda/useFetchGet.ts
  hooks/agenda/useFetchPatch.ts
  hooks/agenda/useFetchPost.ts
  pages/agenda/[agendaKey]/index.tsx
Labels: refactor

#1475 [Feat] agenda 상세정보 공지사항 추가 UI, API 연결 및 useFetchRequest #1470
  components/agenda/Form/CreateAnnouncementForm.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/AnnouncementItem.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  hooks/agenda/useFetchPatch.ts
  hooks/agenda/useFetchPost.ts
  hooks/agenda/useFetchRequest.ts
  pages/agenda/[agendaKey]/host/createAnnouncement.tsx
  styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
  styles/agenda/agendaDetail/tabs/createAnnouncement.module.scss
  types/agenda/agendaDetail/announcementTypes.ts
Labels: enhancement

#1477 [Feat] agenda Info 컴포넌트 조건 추가
  components/agenda/agendaDetail/AgendaInfo.tsx
  styles/agenda/agendaDetail/AgendaInfo.module.scss
  types/agenda/agendaDetail/tabs/agendaInfoTypes.ts
Labels: enhancement

#1472 [Feat] profile page api #1469
  components/agenda/Profile/AgendaHistory.tsx
  components/agenda/Profile/CurrentTeam.tsx
  components/agenda/Profile/CurrentTeamItem.tsx
  components/agenda/Profile/HistoryItem.tsx
  components/agenda/Profile/ParticipatingAgendaItem.tsx
  components/agenda/Profile/ParticipatingTeam.tsx
  components/agenda/Profile/ProfileCard.tsx
  components/agenda/Profile/ProfileContent.tsx
  components/agenda/Profile/ProfileImageCard.tsx
  components/agenda/utils/AgendaTag.tsx
  components/agenda/utils/CustomImage.tsx
  components/agenda/utils/coalition/countCoalitions.tsx
  hooks/agenda/useFetchGet.ts
  pages/agenda/profile/index.tsx
  public/image/agenda/42-icon.svg
  public/image/agenda/Time.svg
  public/image/agenda/edit.svg
  public/image/agenda/github.svg
  styles/agenda/Profile/AgendaHistory.module.scss
  styles/agenda/Profile/CurrentTeam.module.scss
  styles/agenda/Profile/CurrentTeamItem.module.scss
  styles/agenda/Profile/HistoryItem.module.scss
  styles/agenda/Profile/ProfileCard.module.scss
  styles/agenda/Profile/ProfileContent.module.scss
  styles/agenda/Profile/ProfileImageCard.module.scss
  styles/agenda/common.scss
  styles/agenda/utils/AgendaTag.module.scss
  styles/agenda/utils/CustomImage.module.scss
  types/agenda/profile/agendaHistoryTypes.ts
  types/agenda/profile/currentTeamTypes.ts
  types/agenda/profile/profileCardTypes.ts
  types/agenda/profile/profileDataTypes.ts
  types/agenda/utils/customImageTypes.ts
Labels: enhancement, api

#1482 [Feat] 아젠다 전체 리스트 조회 #1479
  Layout/AgendaLayout.tsx
  components/agenda/Form/CreateAgendaForm.tsx
  components/agenda/Home/AgendaInfo.tsx
  components/agenda/Home/AgendaList.tsx
  components/agenda/Home/MyAgendaBtn.tsx
  components/agenda/Home/MyTeamInfo.tsx
  components/agenda/Input/TimeInput.tsx
  components/agenda/utils/AgendaItemBtn.tsx
  pages/_app.tsx
  pages/index.tsx
  styles/agenda/Home/AgendaInfo.module.scss
  styles/agenda/Home/AgendaList.module.scss
  styles/agenda/Home/MyAgendaBtn.module.scss
  styles/agenda/Home/MyTeamInfo.module.scss
  styles/agenda/common.scss
  styles/agenda/utils/AgendaItemBtn.module.scss
  styles/agenda/utils/AgendaTag.module.scss
  styles/color-theme.css
  styles/index.module.scss
  types/agenda/agendaDetail/agendaTypes.ts
  utils/handleTime.ts
Labels: enhancement, api

#1486 [Feat] agenda modal provider 및 기본 UI #1481
  Layout/AgendaLayout.tsx
  Layout/TakguLayout.tsx
  components/agenda/modal/AgendaModalProvider.tsx
  components/agenda/modal/NoticeModal.tsx
  components/agenda/modal/ProceedCheckModal.tsx
  components/agenda/modal/testModal.tsx
  components/agenda/modal/useModal.tsx
  components/tmp/style.module.scss
  pages/_app.tsx
  pages/agenda/index.tsx
  stories/agenda/modal/ProceedCheckModal.stories.tsx
  styles/agenda/common.scss
  styles/agenda/modal/AgendaModalProvider.module.scss
  styles/agenda/modal/modal.module.scss
  types/agenda/modalTypes.ts
  utils/recoil/agenda/modalState.ts
Labels: enhancement

#1487 [Feat] team page api #1474
  components/agenda/Form/CreateTeamForm.tsx
  components/agenda/Input/CheckboxInput.tsx
  components/agenda/Input/DescriptionInput.tsx
  components/agenda/Input/TitleInput.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/teamDetail/TeamButtons.tsx
  components/agenda/teamDetail/TeamInfo.tsx
  constants/agenda/agenda.ts
  pages/agenda/[agendaKey]/[teamUID]/index.tsx
  styles/agenda/TeamDetail/TeamDetail.module.scss
  styles/agenda/TeamDetail/TeamInfo.module.scss
  styles/agenda/button/Buttons.module.scss
  types/aganda/InputPropTypes.ts
  types/agenda/teamDetail/TeamButtonsTypes.ts
  types/agenda/teamDetail/TeamDetailTypes.ts
  types/agenda/teamDetail/TeamInfoTypes.ts
Labels: enhancement, api

#1489 [Feat] 수정 modal 추가 및 클릭 이벤트 에러 처리 #1481
  components/agenda/modal/AgendaModalProvider.tsx
  components/agenda/modal/ModifyModal.tsx
  components/agenda/modal/NoticeModal.tsx
  components/agenda/modal/ProceedCheckModal.tsx
  components/agenda/modal/useModal.tsx
  types/agenda/modalTypes.ts
Labels: bug, enhancement

#1494 [Feat] agenda 스낵바 추가 #1488
  Layout/AgendaLayout.tsx
  Layout/TakguLayout.tsx
  components/takgu/admin/Layout.tsx
  components/toastmsg/toastmsg.tsx
  hooks/useAxiosWithToast.ts
  pages/_app.tsx
  pages/agenda/[agendaKey]/[teamUID]/index.tsx
  utils/agenda/getAgendaSnackBarInfo.ts
Labels: enhancement, api

#1502 [Feat] usepagenation 적용, 버그 및 css 수정 #1498
  components/Layout.tsx
  components/Pagination.tsx
  components/admin/agenda/agendaList/AgendaFillterTab.tsx
  components/admin/agenda/teamList/TeamTable.tsx
  components/admin/takgu/recruitments/recruitmentsDetail/components/ActionSelectorButtons.tsx
  components/agenda/Form/AgendaResultForm.tsx
  components/agenda/Form/SubmitAgendaForm.tsx
  components/agenda/Home/AgendaInfo.tsx
  components/agenda/Home/AgendaList.tsx
  components/agenda/Ticket/Ticket.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/AgendaParticipants.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  components/agenda/utils/PageController.tsx
  components/agenda/utils/team.tsx
  components/tmp/CssTest.tsx
  hooks/agenda/usePageNation.ts
  pages/agenda/[agendaKey]/host/result.tsx
  pages/agenda/index.tsx
  pages/agenda/profile/[intraId]/index.tsx
  stories/agenda/profile/ProfileIndex.stories.tsx
  styles/PageNation.module.scss
  styles/color-theme.css
  styles/globals.css
  types/agenda/agendaDetail/tabs/agendaInfoTypes.ts
Labels: enhancement

#1503 [Feat] admin 팀 수정 페이지 및 api 연결, 팀 삭제
  components/admin/agenda/teamList/TeamTable.tsx
  components/agenda/Form/AdminTeamForm.tsx
  components/agenda/Form/CreateTeamForm.tsx
  components/agenda/utils/formatDate.tsx
  constants/admin/agendaTable.ts
  pages/admin/agenda/teamModify.tsx
  styles/agenda/Form/Form.module.scss
  types/agenda/teamDetail/TeamDetailTypes.ts
Labels: enhancement

#1505 [Fix] 아젠다 상세 페이지 API 호출 기능 수정 #1501
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/tabs/Participant.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  hooks/agenda/useAgendaInfo.ts
  hooks/useAxiosWithToast.ts
  pages/agenda/[agendaKey]/host/index.tsx
  pages/agenda/[agendaKey]/index.tsx
  styles/agenda/agendaDetail/tabs/Participant.module.scss
  styles/agenda/agendaDetail/tabs/ParticipantsList.module.scss
  types/agenda/agendaDetail/tabs/agendaInfoTypes.ts
  utils/agenda/getAgendaSnackBarInfo.ts
Labels: enhancement, api

#1508 [Style] 일부 페이지 반응형 css 적용, padding/margin 전체 정돈
  Layout/AgendaLayout.tsx
  components/agenda/Home/AgendaList.tsx
  components/agenda/Home/AgendaTitle.tsx
  components/agenda/Home/MyAgendaBtn.tsx
  components/agenda/Home/MyTeamInfo.tsx
  components/agenda/Layout/MenuBar.tsx
  components/agenda/Ticket/Ticket.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/AgendaTab.tsx
  components/agenda/utils/PageController.tsx
  components/takgu/Layout/MainPageProfile.tsx
  pages/agenda/[agendaKey]/[teamUID]/index.tsx
  pages/agenda/[agendaKey]/create-team.tsx
  pages/agenda/[agendaKey]/index.tsx
  pages/agenda/create.tsx
  pages/agenda/index.tsx
  pages/index.tsx
  styles/agenda/Home/Agenda.module.scss
  styles/agenda/Home/AgendaDeadLine.module.scss
  styles/agenda/Home/AgendaList.module.scss
  styles/agenda/Home/AgendaTitle.module.scss
  styles/agenda/Home/MyAgendaBtn.module.scss
  styles/agenda/Layout/Layout.module.scss
  styles/agenda/Layout/MenuBar.module.scss
  styles/agenda/TeamDetail/TeamDetail.module.scss
  styles/agenda/Ticket/Ticket.module.scss
  styles/agenda/agendaDetail/AgendaDetail.module.scss
  styles/agenda/agendaDetail/AgendaInfo.module.scss
  styles/agenda/agendaDetail/AgendaTab.module.scss
  styles/agenda/agendaDetail/tabs/AgendaConditions.module.scss
  styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
  styles/agenda/common.scss
  styles/agenda/pages/CreateAgenda.module.scss
  styles/agenda/pages/create-team.module.scss
  styles/agenda/responsive.scss
  styles/agenda/utils/PageController.module.scss
  styles/color-theme.css
  styles/index.module.scss
  styles/takgu/Layout/MainPageProfile.module.scss
  types/agenda/agendaDetail/agendaTypes.ts
Labels: enhancement

#1510 [Feat] admin page #1456
  components/admin/agenda/SideNavAgenda.tsx
  components/admin/agenda/agendaList/AgendaTable.tsx
  components/admin/agenda/teamList/TeamTable.tsx
  components/admin/agenda/ticket/TicketTable.tsx
  components/admin/agenda/users/UserTable.tsx
  components/agenda/Form/AdminTeamForm.tsx
  components/agenda/Form/AdminTicketForm.tsx
  components/agenda/Form/AgendaForm.tsx
  components/agenda/Form/TicketForm.tsx
  components/agenda/Form/userForm.tsx
  components/agenda/Input/AgendaSelect.tsx
  components/agenda/button/Buttons.tsx
  components/agenda/utils/coalition/getCoalitionEnum.tsx
  constants/admin/agendaTable.ts
  pages/admin/agenda/index.tsx
  pages/admin/agenda/teamModify.tsx
  pages/admin/agenda/ticket.tsx
  pages/admin/agenda/userList.tsx
  pages/admin/index.tsx
  pages/admin/takgu/index.tsx
  styles/admin/agenda/TicketTable.module.scss
  styles/admin/index.module.scss
  styles/agenda/Form/Form.module.scss
  types/agenda/agendaDetail/tabs/participantTypes.ts
  types/agenda/ticket/ticketTypes.ts
Labels: enhancement
