Repository 42organization/42gg.client, pull requests merged in 2024-09, with the labels that each got.

#1524 [Fix] agenda 상세정보 bug fix #1521
  components/admin/agenda/announcements/AnnouncementTable.tsx
  components/agenda/Form/AdminTicketForm.tsx
  components/agenda/agendaDetail/TabContent.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/AgendaDescription.tsx
  components/agenda/agendaDetail/tabs/AgendaParticipants.tsx
  components/agenda/agendaDetail/tabs/AgendaPoster.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  constants/agenda/agendaDetail/agendaTabs.ts
  public/image/buttons/addElem.svg
  public/image/buttons/cancel.svg
  public/image/buttons/delete.svg
  public/image/buttons/drag.svg
  public/image/buttons/removeElem.svg
  public/image/buttons/share.svg
  public/image/buttons/toLeft.svg
  public/image/buttons/toRight.svg
  styles/agenda/agendaDetail/AgendaTab.module.scss
  styles/agenda/agendaDetail/tabs/AgendaAnnouncements.module.scss
  styles/agenda/agendaDetail/tabs/ParticipantTeamList.module.scss
  styles/agenda/agendaDetail/tabs/ParticipantsList.module.scss
  styles/agenda/button/Buttons.module.scss
  types/agenda/agendaDetail/agendaTypes.ts
  types/agenda/agendaDetail/tabs/participantTypes.ts
Labels: fix

#1535 [Bug] 팀 상세 페이지 토스트 에러 #1522
  components/agenda/teamDetail/TeamButtons.tsx
  hooks/useAxiosWithToast.ts
  pages/agenda/[agendaKey]/[teamUID]/index.tsx
  utils/agenda/getAgendaSnackBarInfo.ts
Labels: enhancement, api

#1537 [Fix] agenda admin #1531
  Layout/AdminLayout.tsx
  Layout/AgendaLayout.tsx
  Layout/TakguLayout.tsx
  components/admin/agenda/SideNavAgenda.tsx
  components/admin/agenda/agendaList/AgendaFillterTab.tsx
  components/admin/agenda/agendaList/AgendaTable.tsx
  components/admin/agenda/announcements/AnnouncementTable.tsx
  components/admin/agenda/teamList/TeamTable.tsx
  components/agenda/Form/AdminTicketForm.tsx
  components/agenda/Form/TicketForm.tsx
  components/agenda/Form/userForm.tsx
  components/agenda/Home/AgendaInfo.tsx
  components/agenda/Home/MyTeamInfo.tsx
  components/agenda/Input/AgendaSelect.tsx
  components/agenda/Profile/HistoryList.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/modal/NoticeModal.tsx
  components/agenda/utils/AgendaTag.tsx
  constants/admin/agendaTable.ts
  constants/agenda/agenda.ts
  hooks/agenda/usePageNation.ts
  pages/admin/agenda/teamModify.tsx
  styles/agenda/Form/Form.module.scss
  styles/agenda/Layout/Layout.module.scss
  styles/agenda/agendaDetail/AgendaInfo.module.scss
  styles/agenda/agendaDetail/tabs/AgendaConditions.module.scss
  styles/agenda/agendaDetail/tabs/ParticipantsList.module.scss
  styles/agenda/button/TabButton.module.scss
  styles/agenda/common.scss
  styles/agenda/modal/AgendaModalProvider.module.scss
  styles/agenda/modal/modal.module.scss
  styles/agenda/pages/create-team.module.scss
  styles/agenda/utils/AgendaTag.module.scss
  types/agenda/modalTypes.ts
Labels: fix

#1541 [Bug] router bug #1538
  components/LoginChecker.tsx
  components/agenda/Form/CreateTeamForm.tsx
  components/agenda/Form/SubmitAgendaForm.tsx
  components/agenda/Home/AgendaList.tsx
  components/agenda/Home/MyTeamInfo.tsx
  components/agenda/Layout/MenuBar.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/agendaDetail/tabs/AgendaAnnouncements.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeam.tsx
  components/agenda/agendaDetail/tabs/ParticipantTeamList.tsx
  components/agenda/agendaDetail/tabs/ParticipantsList.tsx
  components/agenda/teamDetail/TeamInfo.tsx
  components/agenda/utils/AgendaLoading.tsx
  components/agenda/utils/PageController.tsx
  hooks/agenda/useAgendaInfo.ts
  hooks/agenda/useAgendaKey.ts
  hooks/agenda/useAgendaTeamKey.ts
  hooks/agenda/useFetchGet.ts
  hooks/agenda/usePageNation.ts
  pages/agenda/detail/host/createAnnouncement.tsx
  pages/agenda/detail/host/index.tsx
  pages/agenda/detail/host/result.tsx
  pages/agenda/detail/index.tsx
  pages/agenda/detail/team/create.tsx
  pages/agenda/detail/team/index.tsx
  pages/agenda/profile/index.tsx
  pages/agenda/profile/user.tsx
  stories/agenda/Form/CreateTeam.stories.tsx
  stories/agenda/Form/SubmitAgendaResult.stories.tsx
  styles/agenda/utils/AgendaLoading.module.scss
Labels: enhancement, refactor, api

#1555 [Fix] 아젠다 리스트, 호스트페이지, 상세조회 페이지 버그 #1551
  components/agenda/Form/AgendaForm.tsx
  components/agenda/Form/SubmitAgendaForm.tsx
  components/agenda/agendaDetail/TabContent.tsx
  components/agenda/agendaDetail/tabs/AgendaDescription.tsx
  constants/agenda/agendaDetail/agendaTabs.ts
  pages/agenda/detail/host/index.tsx
  pages/agenda/index.tsx
  styles/agenda/agendaDetail/AgendaDetail.module.scss
  styles/agenda/agendaDetail/tabs/AgendaConditions.module.scss
  styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
  styles/agenda/pages/agendakey/host/host.module.scss
Labels: enhancement, fix

#1557 [Fix] 프로필 페이지 API 호출 로직 수정
  components/agenda/Home/AgendaList.tsx
  components/agenda/Ticket/Ticket.tsx
  components/agenda/agendaDetail/AgendaInfo.tsx
  components/agenda/utils/PageController.tsx
  components/takgu/Layout/Header.tsx
  components/toastmsg/toastmsg.tsx
  hooks/agenda/useFetchGet.ts
  pages/agenda/profile/user.tsx
  styles/agenda/common.scss
  styles/globals.css
  types/agenda/profile/profileCardTypes.ts
Labels: enhancement, refactor, api

#1560 [Fix] 프로필 update 오류, 팀 수정 폼 변경, css 정리 #1551
  components/agenda/Form/AdminTeamForm.tsx
  components/agenda/Profile/CurrentList.tsx
  components/agenda/agendaDetail/tabs/AgendaDescription.tsx
  components/agenda/agendaDetail/tabs/Participant.tsx
  components/error/AgendaError.tsx
  hooks/agenda/usePageNation.ts
  pages/agenda/profile/user.tsx
  pages/agenda/ticket/history.tsx
  styles/agenda/Home/AgendaInfo.module.scss
  styles/agenda/Home/AgendaList.module.scss
  styles/agenda/Layout/Layout.module.scss
  styles/agenda/Profile/AgendaProfile.module.scss
  styles/agenda/Profile/CurrentList.module.scss
  styles/agenda/Profile/HistoryList.module.scss
  styles/agenda/Profile/ProfileCard.module.scss
  styles/agenda/agendaDetail/AgendaDetail.module.scss
  styles/agenda/agendaDetail/tabs/AgendaDescription.module.scss
  styles/agenda/utils/AgendaTag.module.scss
Labels: fix

#1562 [Style] responsive profile page #1553
  components/agenda/Profile/CurrentList.tsx
  components/agenda/Profile/HistoryList.tsx
  pages/agenda/profile/user.tsx
  styles/agenda/Profile/AgendaProfile.module.scss
  styles/agenda/Profile/CurrentList.module.scss
  styles/agenda/Profile/HistoryList.module.scss
  types/agenda/profile/historyListTypes.ts
Labels: enhancement
