Repository 42organization/42gg.client, pull requests merged in 2024-03, with the labels that each got.

#1249 Feat: Admin PartyRoom 타입 및 상태관리 구현
  components/party/PartyNav.tsx
  components/party/PartyRoom.tsx
  components/party/PartyRoomEdit.tsx
  constants/admin/table.ts
  hooks/party/usePartyList.ts
  package.json
  pages/api/pingpong/party/admin/rooms/[roomId]/index.ts
  pages/api/pingpong/party/admin/rooms/index.ts
  pages/api/pingpong/party/rooms/index.ts
  styles/admin/party/PartyRoomEdit.module.scss
  styles/admin/party/PartyRoomTable.module.scss
  types/admin/adminParty.ts
  types/admin/tableTypes.ts
  types/partyTypes.ts
Labels: enhancement

#1255 [Feat] 유저 페이지 레이아웃 구성
  components/Layout/Layout.tsx
  components/Layout/MenuBar/MenuBarElement.tsx
  components/Layout/PlayButton.tsx
  components/Layout/UserLayout.tsx
  components/recruit/RecruitLayout.tsx
  hooks/recruit/useCheckRecruit.ts
  package-lock.json
  package.json
  pages/api/pingpong/recruitments/index.ts
  pages/recruit/index.tsx
  public/image/menu_recruit.svg
  public/lottie/recruitPingPong.json
  styles/Layout/MenuBar.module.scss
  styles/common.scss
  styles/recruit/common.module.scss
  styles/recruit/common.scss
  styles/recruit/layout.module.scss
  styles/recruit/text.module.scss
  types/recruit/recruitments.d.ts
Labels: user, recruit

#1252 [Feat] 공고페이지 레이아웃 구성 #1246
  components/admin/SideNav.tsx
  components/admin/recruitments/recruitmentsHistoryList.tsx
  components/admin/recruitments/recruitmentsMain.tsx
  components/admin/recruitments/recruitmentsuser/detailRecruitUserList.tsx
  components/admin/recruitments/recruitmentsuser/menuTab.tsx
  components/admin/recruitments/recruitmentsuser/notificationResults.tsx
  constants/admin/table.ts
  package-lock.json
  package.json
  pages/admin/recruitments.tsx
  pages/api/pingpong/admin/recruit/index.ts
  pages/api/pingpong/admin/recruitments/[id].ts
  pages/api/pingpong/admin/recruitments/index.ts
  styles/admin/recruitments/MenuTab.module.scss
  styles/admin/recruitments/Recruitments.module.scss
  types/admin/adminRecruitmentsTypes.ts
  types/admin/tableTypes.ts
Labels: admin, recruit

#1258 [Feat] 지원서 작성 페이지 레이아웃 구성 #1251
  components/recruit/ApplicationForm.tsx
  hooks/recruit/useRecruitDetail.ts
  pages/api/pingpong/recruitments/[id].ts
  pages/recruit/application.tsx
  styles/recruit/application.module.scss
  types/recruit/recruitments.d.ts
Labels: user, recruit

#1264 category 관리 훅 구현
  components/Layout/Layout.tsx
  components/party/PartyNav.tsx
  components/party/PartyRoomEdit.tsx
  components/party/PartyRoomList.tsx
  components/party/PartyRoomTable.tsx
  hooks/party/usePartyCategory.ts
  hooks/party/usePartyList.ts
  pages/api/pingpong/party/admin/rooms/index.ts
  pages/parties/index.tsx
  styles/admin/party/PartyRoomEdit.module.scss
  styles/party/PartyMain.module.scss
  styles/party/ParytyRoomList.module.scss
  types/admin/adminParty.ts
  types/partyTypes.ts
Labels: enhancement

#1270 Feat: PartyCreate페이지 작성 및 usePartyTemplate 훅 구현
  components/party/PartyCreate.tsx
  hooks/party/usePartyCategory.ts
  hooks/party/usePartyTemplate.ts
  pages/api/pingpong/party/templates.ts
  pages/parties/create.tsx
  styles/party/PartyCreate.module.scss
  types/partyTypes.ts
Labels: enhancement

#1271 Party board
  components/modal/Party/PartyCommentModal.tsx
  components/modal/Party/PartyReportModal.tsx
  components/modal/modalType/PartyReportModal.tsx
  components/party/PartyRoomDetail.tsx
  pages/api/pingpong/party/rooms/[partyId]/index.ts
  pages/api/pingpong/party/rooms/[partyId]/start/index.ts
  pages/parties/[partyId]/index.tsx
  styles/modal/party/PartyReportModal.module.scss
  types/modalTypes.ts
  utils/handleTime.ts
Labels: enhancement, admin

#1276 Feat: Party관련 모달 설정
  components/modal/ModalProvider.tsx
  components/modal/modalType/AdminModal.tsx
  components/modal/modalType/PartyModal.tsx
  components/modal/party/PartyRoomEditModal.tsx
  components/party/PartyRoomTable.tsx
  pages/parties/index.tsx
  styles/admin/party/PartyRoomEdit.module.scss
  types/modalTypes.ts
  utils/recoil/modal.ts
Labels: enhancement

#1277 Devjaeywon
  components/party/PartyCategory.tsx
  components/party/PartyCommentReport.tsx
  components/party/PartyNav.tsx
  components/party/PartyNoShowReport.tsx
  components/party/PartyPenalty.tsx
  components/party/PartyReport.tsx
  components/party/PartyReportNav.tsx
  components/party/PartyRoomReport.tsx
  components/party/PartyTemplate.tsx
  components/party/TemplateModal.tsx
  constants/admin/table.ts
  pages/api/pingpong/party/admin/rooms/reports/rooms/index.ts
  pages/api/pingpong/party/templates.ts
  styles/party/PartyNav.module.scss
  styles/party/ParytyRoomList.module.scss
  styles/party/TemplateModal.module.scss
  types/admin/tableTypes.ts
  types/partyTypes.ts
Labels: enhancement

#1282 Party board
  components/modal/Party/PartyCommentModal.tsx
  components/modal/Party/PartyReportModal.tsx
  components/modal/modalType/PartyModal.tsx
  components/modal/modalType/PartyReportModal.tsx
  components/party/PartyRoomDetail.tsx
  types/modalTypes.ts
  types/partyTypes.ts
Labels: enhancement

#1265 Feat 관리자 공고 등록 수정 템플릿 #1256
  components/UI/DraggableList.tsx
  components/admin/recruitments/RecruitmentsHistoryList.tsx
  components/admin/recruitments/RecruitmentsMain.tsx
  components/admin/recruitments/recruitmentsEdit/RecruitmentEdit.tsx
  components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
  components/admin/recruitments/recruitmentsEdit/components/QuestionFormBuilder.tsx
  components/admin/recruitments/recruitmentsEdit/components/QuillDescriptionEditor.tsx
  components/admin/recruitments/recruitmentsEdit/components/TitleTimeRangeSelector.tsx
  components/admin/recruitments/recruitmentsMain.tsx
  components/admin/recruitments/recruitmentsuser/DetailRecruitUserList.tsx
  components/admin/recruitments/recruitmentsuser/MenuTab.tsx
  components/admin/recruitments/recruitmentsuser/NotificationResults.tsx
  constants/admin/table.ts
  hooks/recruitments/useRecruitmentEditInfo.ts
  package-lock.json
  package.json
  pages/admin/recruitments.tsx
  pages/api/pingpong/admin/recruit/index.ts
  styles/UI/DraggableList.module.scss
  styles/admin/recruitments/recruitmentEdit/RecruitmentEdit.module.scss
  styles/admin/recruitments/recruitmentEdit/components/ActionSelectorButtons.module.scss
  styles/admin/recruitments/recruitmentEdit/components/QuestionFormBuilder.module.scss
  styles/admin/recruitments/recruitmentEdit/components/QuillDescriptionEditor.module.scss
  styles/admin/recruitments/recruitmentEdit/components/TitleTimeRangeSelector.module.scss
  types/admin/adminRecruitmentsTypes.ts
  types/admin/tableTypes.ts
Labels: enhancement, admin, recruit

#1287 [Feat] party category api사용 hook 구현
  hooks/party/usePartyCategory.ts
  utils/axios.ts
Labels: enhancement, admin, user

#1289 [Feat] partytemplate api사용 hook 구현
  hooks/party/usePartyTemplate.ts
Labels: enhancement, admin, user

#1303 [Feat] 상황별 공고 메인 페이지
  components/recruit/Main/CollapseListItem.tsx
  components/recruit/Main/MyApplicationInfo.tsx
  components/recruit/Main/MyRecruitStatus.tsx
  components/recruit/Main/MyRecruitment.tsx
  components/recruit/Main/RecruitStepper.tsx
  hooks/recruit/useGetRecruitResult.ts
  hooks/recruit/useRecruitDetail.ts
  pages/api/pingpong/recruitments/[id]/applications/result/index.ts
  pages/recruit/[id]/index.tsx
  styles/recruit/Main/collapseListItem.module.scss
  styles/recruit/Main/myRecruitment.module.scss
  styles/recruit/RecruitList/list.module.scss
  types/recruit/recruitments.d.ts
  utils/handleTime.ts
Labels: user, recruit

#1299 Feat 관리자 공고 등록 수정 템플릿 #1256
  components/admin/recruitments/recruitmentsEdit/RecruitmentEdit.tsx
  components/admin/recruitments/recruitmentsEdit/components/ActionSelectorButtons.tsx
  components/admin/recruitments/recruitmentsEdit/components/QuestionFormBuilder.tsx
  components/admin/recruitments/recruitmentsEdit/components/QuillDescriptionEditor.tsx
  components/admin/recruitments/recruitmentsEdit/components/TitleTimeRangeSelector.tsx
  hooks/recruitments/useRecruitmentEditInfo.ts
  styles/admin/recruitments/recruitmentEdit/components/ActionSelectorButtons.module.scss
  styles/admin/recruitments/recruitmentEdit/components/QuestionFormBuilder.module.scss
  styles/admin/recruitments/recruitmentEdit/components/QuillDescriptionEditor.module.scss
Labels: enhancement, admin, recruit

#1304 Feat/메인페이지 파티모집프리뷰구현 어드민페이지지pr용 #1300
  components/admin/SideNav.tsx
  components/admin/party/AdminCommentReport.tsx
  components/admin/party/AdminPartyNoShow.tsx
  components/admin/party/AdminPartyRoomReport.tsx
  components/admin/party/PartyCategory.tsx
  components/admin/party/PartyNav.tsx
  components/admin/party/PartyReportNav.tsx
  components/admin/party/PartyTemplate.tsx
  components/main/PartyPreview.tsx
  components/main/Section.tsx
  components/modal/Party/TemplateModal.tsx
  components/modal/modalType/AdminModal.tsx
  constants/admin/table.ts
  hooks/party/useAdminPartyComment.tsx
  hooks/party/useAdminPartyNoShow.tsx
  hooks/party/useAdminPartyRoomReport.tsx
  hooks/party/usePartyRoomList.tsx
  pages/admin/party.tsx
  pages/index.tsx
  styles/admin/Party/AdminPartyCommon.module.scss
  styles/main/PartyPreview.module.scss
  styles/party/PartyNav.module.scss
  styles/party/TemplateModal.module.scss
  types/admin/tableTypes.ts
  types/modalTypes.ts
  types/partyTypes.ts
Labels: enhancement, admin, user

#1307 [Feat] party모집 서비스의 메인 페이지 구현 #1280
  components/Layout/Layout.tsx
  components/party/PartyRoomListItem.tsx
  hooks/party/usePartyRoomList.ts
  pages/party/index.tsx
  public/image/party-background.png
  styles/Layout/Layout.module.scss
  styles/party/PartyCommon.scss
  styles/party/PartyMain.module.scss
  styles/party/PartyRoomListItem.module.scss
  types/colorModeTypes.ts
  types/partyTypes.ts
Labels: enhancement, user

#1306 [Feat] 지원 결과 상태 추가
  components/recruit/Main/MyRecruitStatus.tsx
  components/recruit/Main/MyRecruitment.tsx
  components/recruit/Main/RecruitStepper.tsx
  hooks/recruit/useGetRecruitResult.ts
  pages/api/pingpong/recruitments/[id].ts
  pages/api/pingpong/recruitments/[id]/applications/[applicationId]/result.ts
  pages/recruit/[id]/index.tsx
  types/recruit/recruitments.d.ts
Labels: user, recruit

#1311 Feat/make party detail #1283
  components/modal/Party/PartyReportModal.tsx
  components/party/roomDetail/PartyDetailButton.tsx
  components/party/roomDetail/PartyDetailContentCommentBox.tsx
  components/party/roomDetail/PartyDetailProfile.tsx
  components/party/roomDetail/PartyDetailTitleBox.tsx
  pages/api/pingpong/party/rooms/[roomId]/index.ts
  pages/api/pingpong/party/rooms/[roomId]/start/index.ts
  pages/party/[roomId]/index.tsx
  styles/party/PartyDetailRoom.module.scss
  types/modalTypes.ts
  types/partyTypes.ts
  utils/handleTime.ts
Labels: enhancement, user

#1312 [Feat] party 배경 이미지 설정 hook
  hooks/party/usePartyColorMode.ts
Labels: enhancement, user

#1314 [Feat] party모집 방 생성 페이지 구현 #1281
  components/party/PartyCreate.tsx
  constants/party/createOptions.ts
  hooks/party/usePartyCategory.ts
  pages/party/create.tsx
  styles/party/PartyCreate.module.scss
Labels: enhancement, user

#1316 [Hotfix] category, template api 리스트에 키값 추가
  hooks/party/usePartyCategory.ts
  hooks/party/usePartyTemplate.ts
Labels: user, hotfix

#1319 Update main-deploy.yml
  .github/workflows/main-deploy.yml
Labels: deploy

#1313 [Feat] 지원서 보기,수정,취소 기능
  components/modal/recruitment/ApplyEditModal.tsx
  components/modal/recruitment/ApplyModal.tsx
  components/modal/recruitment/CancelModal.tsx
  components/recruit/Application/ApplicationForm.tsx
  components/recruit/Application/ApplicationLoadingNoData.tsx
  components/recruit/Application/ApplicationSnackBar.tsx
  components/recruit/Application/applicationFormItems/MultiCheckForm.tsx
  components/recruit/Application/applicationFormItems/SingleCheckForm.tsx
  components/recruit/Application/applicationFormItems/TextForm.tsx
  components/recruit/Application/applicationLayout/ApplicationFormFooter.tsx
  components/recruit/Application/applicationLayout/ApplicationFormHeader.tsx
  components/recruit/ApplicationForm.tsx
  components/recruit/ApplicationQuestions.tsx
  components/recruit/Main/MyApplicationInfo.tsx
  components/recruit/RecruitLayout.tsx
  hooks/recruit/useRecruitDetail.ts
  hooks/recruit/useRecruitDetailUser.ts
  hooks/recruit/useUserApplicationForm.ts
  pages/api/pingpong/recruitments/[id].ts
  pages/api/pingpong/recruitments/[id]/applications.ts
  pages/api/pingpong/recruitments/[id]/applications/[applicationId].ts
  pages/api/pingpong/recruitments/index.ts
  pages/recruit/[id]/apply.tsx
  pages/recruit/[id]/index.tsx
  pages/recruit/[id]/my-application.tsx
  pages/recruit/application.tsx
  styles/modal/recruit/recruitModal.module.scss
  styles/recruit/application.module.scss
  tsconfig.json
  types/recruit/recruitments.d.ts
  utils/handleApplicationForm.ts
  utils/recoil/application.ts
Labels: user, recruit

#1318 [Fix] 세부 내역 방 버그 #1317
  .github/workflows/test-deploy.yml
  components/modal/Party/PartyReportModal.tsx
  components/modal/modalType/PartyModal.tsx
  components/party/roomDetail/PartyDetailButton.tsx
  components/party/roomDetail/PartyDetailContentCommentBox.tsx
  components/party/roomDetail/PartyDetailProfile.tsx
  components/party/roomDetail/PartyDetailTitleBox.tsx
  pages/party/[roomId]/index.tsx
  styles/party/PartyDetailRoom.module.scss
Labels: bug, enhancement

#1325 [Fix] 프리뷰 선택시 navigate설정, 배경이미지 추가
  components/main/PartyPreview.tsx
  styles/main/PartyPreview.module.scss
Labels: user

#1330 Feat/party room admin 페이지 구현 #1247
  components/admin/party/PartyNav.tsx
  components/admin/party/PartyRoomTable.tsx
  components/modal/Party/PartyRoomEditModal.tsx
  components/modal/modalType/AdminModal.tsx
  hooks/party/useAdminPartyRoomList.ts
  hooks/party/usePartyRoomList.ts
  hooks/party/usePartyRoomList.tsx
  styles/admin/Party/PartyRoomEdit.module.scss
  types/admin/adminPartyTypes.ts
  types/admin/tableTypes.ts
  types/modalTypes.ts
  types/partyTypes.ts
Labels: enhancement, admin

#1331 [Bug] 파티 메인 페이지 전체 필터 적용안되는 오류 수정
  pages/party/index.tsx
Labels: bug, user

#1332 [Feat] 메인 페이지 마감시간 표시 및 진행중 표기
  components/party/PartyRoomListItem.tsx
  pages/party/index.tsx
  styles/party/PartyCommon.scss
  styles/party/PartyMain.module.scss
  styles/party/PartyRoomListItem.module.scss
Labels: bug, enhancement, user

#1333 [Feat] 파티 생성 페이지 배경 설정 및 글자수 표기
  components/party/PartyCreate.tsx
  styles/Layout/Layout.module.scss
  styles/party/PartyCreate.module.scss
  types/partyTypes.ts
Labels: enhancement, user

#1336 [Fix] 시간출력오류 변경
  components/admin/party/AdminCommentReport.tsx
  components/admin/party/AdminPartyNoShow.tsx
  components/admin/party/AdminPartyPenalty.tsx
  components/admin/party/AdminPartyRoomReport.tsx
  components/admin/party/PartyTemplate.tsx
  components/modal/admin/AdminPartyPenaltyModal.tsx
  components/modal/modalType/AdminModal.tsx
  types/modalTypes.ts
  types/partyTypes.ts
Labels: admin
