Repository 42organization/42gg.client, pull requests merged in 2024-01, with the labels that each got.

#1218 [Others] 예정 진행중 토너먼트 데이터 fetching 리팩토링 #1024
  components/main/Section.tsx
  components/main/TournamentPreview.tsx
  components/main/TournamentPreview/TournamentPreviewItem.tsx
  components/tournament/TournamentCard.tsx
  hooks/tournament/useBeforeLiveTournamentData.ts
  pages/index.tsx
  pages/tournament.tsx
  styles/main/TournamentPreview.module.scss
  styles/main/TournamentPreview/TournamentPreviewItem.module.scss
  styles/tournament/TournamentCard.module.scss
  styles/tournament/TournamentContainer.module.scss
Labels: user, refactor

#1228 Others/관리자 토너먼트 생성 수정시 분단위로 설정 할수 있도록 수정 #1225
  components/admin/tournament/TournamentEdit.tsx
  hooks/tournament/useTournamentEditInfo.ts
Labels: admin, refactor

#1229 [Fix] 관리자 피드백 처리 상태 변경 시 알림 전송 선택 기능 오작동 수정 #1126
  components/modal/admin/AdminFeedbackCheckModal.tsx
Labels: bug, admin

#1224 [Others] Rank 페이지 조회, 경험치 랭킹 페이지 조회 API URL 변경 #1223
  components/rank/RankList.tsx
Labels: user, refactor

#1227 [Others] 토너먼트 브라켓 및 스와이퍼 로딩 컴포넌트 적용 #1203
  components/UI/LoadingSpinner.tsx
  components/tournament-record/WinnerSwiper.tsx
  components/tournament-record/WinnerTournamentInfo.tsx
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentCard.tsx
  components/tournament/UserTournamentBracket.tsx
  pages/tournament-record.tsx
  pages/tournament.tsx
  styles/UI/LoadingSpinner.module.scss
  styles/tournament-record/TournamentRecord.module.scss
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/UserTournamentBracket.module.scss
  utils/handleBraketSize.ts
  utils/infinityScroll.ts
Labels: user, refactor

#1234 [Feat] 슬랙 알림 기능 활성화 #1233
  components/modal/profile/EditProfileModal.tsx
Labels: enhancement, user

#1237 test deploy
  components/UI/LoadingSpinner.tsx
  components/modal/admin/AdminFeedbackCheckModal.tsx
  components/modal/profile/EditProfileModal.tsx
  components/rank/RankList.tsx
  components/tournament-record/WinnerSwiper.tsx
  components/tournament-record/WinnerTournamentInfo.tsx
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentCard.tsx
  components/tournament/UserTournamentBracket.tsx
  pages/tournament-record.tsx
  pages/tournament.tsx
  styles/UI/LoadingSpinner.module.scss
  styles/tournament-record/TournamentRecord.module.scss
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/UserTournamentBracket.module.scss
  utils/handleBraketSize.ts
  utils/infinityScroll.ts
Labels: test deploy

#1238 deploy
  components/UI/LoadingSpinner.tsx
  components/modal/profile/EditProfileModal.tsx
  components/rank/RankList.tsx
  components/tournament-record/WinnerSwiper.tsx
  components/tournament-record/WinnerTournamentInfo.tsx
  components/tournament/TournamentBraket.tsx
  components/tournament/TournamentCard.tsx
  components/tournament/UserTournamentBracket.tsx
  pages/tournament-record.tsx
  pages/tournament.tsx
  styles/UI/LoadingSpinner.module.scss
  styles/tournament-record/TournamentRecord.module.scss
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/UserTournamentBracket.module.scss
  utils/handleBraketSize.ts
  utils/infinityScroll.ts
Labels: deploy

#1236 [Others] 토너먼트 점수 입력 혹은 경기 종료 후 경기 진행 상황 업데이트 #1210
  components/tournament/UserTournamentBracket.tsx
  pages/tournament.tsx
  styles/tournament/UserTournamentBracket.module.scss
Labels: user

#1240 [Fix] LIVE 상태인 토너먼트 모두 표시 #1239
  pages/tournament.tsx
  styles/tournament/UserTournamentBracket.module.scss
Labels: bug, user

#1241 테스트서버 배포
  components/modal/modalType/TournamentModal.tsx
  components/modal/tournament/TournamentManualModal.tsx
  components/tournament/UserTournamentBracket.tsx
  pages/tournament.tsx
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/UserTournamentBracket.module.scss
  types/modalTypes.ts
Labels: test deploy

#1242 메인서버 배포
  components/modal/modalType/TournamentModal.tsx
  components/modal/tournament/TournamentManualModal.tsx
  components/tournament/UserTournamentBracket.tsx
  pages/tournament.tsx
  styles/tournament/TournamentContainer.module.scss
  styles/tournament/UserTournamentBracket.module.scss
  types/modalTypes.ts
Labels: deploy
